version: '3'

services:
  logging-server:
    build:
      context: .
      dockerfile:  Dockerfile
    container_name: logging-server
    image: logging-server
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - '3000:5000'
  api-server:
    build:
      context: .
      dockerfile:  Dockerfile
    container_name: api-server
    image: api-server
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - '5000:5000'

networks:
  app-network:
    driver: bridge
